# Generated by Django 4.2.3 on 2023-07-26 05:17

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryName', models.CharField(max_length=255)),
                ('sub_category_img', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth_app.categories')),
            ],
            options={
                'db_table': 'subcategories',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='Subcategory_detail', to='cloth_app.subcategory'),
        ),
    ]
