# Generated by Django 4.2.2 on 2023-08-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0002_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
