# Generated by Django 4.2.2 on 2023-07-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0002_customuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jwt_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='token',
        ),
    ]
