# Generated by Django 4.2.3 on 2023-07-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0002_subcategory_categories_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage for the offer', max_digits=5, null=True),
        ),
    ]
