# Generated by Django 4.2.3 on 2023-07-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0003_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategoryName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cloth_app.subcategory'),
        ),
    ]
