# Generated by Django 4.2.3 on 2023-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0004_product_subcategoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], default='K', max_length=1),
        ),
    ]
