# Generated by Django 4.2.3 on 2023-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_price',
            field=models.IntegerField(default=0),
        ),
    ]
