# Generated by Django 4.2.3 on 2023-07-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_app', '0008_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
